sudo: false

language: cpp

os:
  - osx

env:
  - BOTTLE_PACKAGE="gtk+3"
  - BOTTLE_PACKAGE="clutter-gtk"

compiler:
  - clang
#  - gcc

# Only build the master branch, otherwise once the release is added, Github
# creates a tag which triggers another identical build.
branches:
  only:
    - master

before_install:
  - brew update

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - brew unlink $BOTTLE_PACKAGE || true

script:
  - travis_wait 45 brew install --build-bottle $BOTTLE_PACKAGE
  - brew bottle $BOTTLE_PACKAGE

before_deploy:
  - export RELEASE_FILES=$(ls *.bottle*.tar.gz)
  - "echo 'Deploying files to Github: '$RELEASE_FILES"
  - du -h $RELEASE_FILES

deploy:
  provider: releases
  api_key:
    secure: 4Ww+znhFTom6rS6WQzzOs4Ck5mwygCVCbGKQl8OFoxCLXAi1IG3UeeRzQxFRSSDTMW97lQXbhFWxkkqGBDjtxkvw+4KTyl2xjyXHkQ2DbiAOOB82M2YoYvtF+WZbXlMhgXWQ/+nPjQXLmqH53HqoknTzU6HwXY1/ZlkvysSyjJhgdt52642uoqyTbC/yLOl8Pu/i92sersYYj8l278fhgUxNgRSUmKxDRVy9l167NYp1CkbRjSgpRMmRXRkMIFOeZvZNUwjujfJ4DLxyaTa7v2gptzrtZ22lZctEKBuo6ECzjJ4pQT5kRjVqGR4SKrvcOCemi0ePoY7EWGZ2tPTW39Q1Taeu+pVNdIxWhOzKzFvQI3T5zjS1uyZJueXX8K2qQRwKQIOyA25kU6wfK8oUvWk2hgHSeh1NMrU/DsBs6Qqe/ra/5CFTVedxLDO1WfG4V/qwBEjBGR1BJ9JyCT9R2txh+O8kQwmRKBrqGBOt+oV0dpCb/OO+Hc6BykZSi0BFXH1BFXkNDVmQ76rEhMuozYxVwoQBeK9S6iq5zm4KDdOWgK5rm6+lPVLIyU+efHR7ovSFBxz9T2/DJM9qpnOojfFnaEDzBSBPRoM4USAEpcxU82OpQRJJQefb0riki7WOdJRFyPzQeHXLlrhfw7X5VmO5rlJ5n6N3y1G/iMHGIXg=
  file: "${RELEASE_FILES}"
  skip_cleanup: true
  on:
    repo: project-renard/travis-homebrew-bottle
  overwrite: true
